{% set name = "polytri" %}
{% set version = "0.1.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build_number }}
  script:
    - bash build.sh  # Unix-like systems
    - bld.bat        # Windows

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust
    - maturin >=1.0,<2.0
    - pip
    - python >=3.8
    - setuptools
    - wheel

  host:
    - python >=3.8
    - pip
    - numpy
    - setuptools
    - wheel

  run:
    - python >=3.8
    - numpy

test:
  imports:
    - polytri
    - polytri._python
    - polytri._rust
  commands:
    - python -c "import polytri; assert polytri._rust_available or polytri._python_available"
    - python -c "from polytri import PolyTri; print('PolyTri imported successfully')"
    - python -c "from polytri import PolyTriPy; print('PolyTriPy imported successfully')"
  requires:
    - pytest
    - numpy
    - matplotlib

about:
  home: https://github.com/openglider/poly-tri
  license: MIT
  license_file: LICENSE
  summary: Delaunay triangulation with constrained boundaries and hole removal
  description: |
    PolyTri is a high-performance Delaunay triangulation library with support for
    constrained boundaries and hole removal. It provides both a Rust implementation
    (faster) and a Python implementation (fallback).
    
    Features:
    - Fast Delaunay triangulation (Rust implementation)
    - Constrained boundary support
    - Hole removal
    - Python fallback implementation
  doc_url: https://github.com/openglider/poly-tri
  dev_url: https://github.com/openglider/poly-tri

extra:
  recipe-maintainers:
    - openglider

